#!/bin/bash

export BASH_SILENCE_DEPRECATION_WARNING=1
export HOME_BIN=$HOME/.local/bin

source .env

REPO_CONFIG_DIR=./config
REPO_SCRIPT_DIR=./scripts

HOME_LOCAL_DIR=${HOME}/.local
HOME_TB_DIR=${HOME_LOCAL_DIR}/tb
HOME_BIN_DIR=${HOME_LOCAL_DIR}/bin
HOME_BUILD_DIR=${HOME_LOCAL_DIR}/build

# Colors
red=$(tput setaf 1)
green=$(tput setaf 2)
blue=$(tput setaf 4)
purple=$(tput setaf 5)
reset=$(tput sgr0)

# Bash Prompt
PS1="\[$red\]\D{%H:%M:%S} \[$green\]\u@\h\[$reset\] \[$purple\]\w\[$reset\] $ "


# Highlight ls color
export CLICOLOR=1
alias ls='ls -G'
alias ll='ls -lG'

PATH="${PATH}:${HOME_BIN}"
export PATH

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Misc Environment Variables
EXTERNAL_IP=69.212.62.235
HOMELAB_IP=69.212.62.235

# Aliases
alias dc="docker"
alias nvimedit="nvim ~/.config/nvim/init.vim"
alias vim="nvim"
alias cr="cargo run"
alias ct="cargo test"
alias crb="RUST_BACKTRACE=1 cargo run"
alias pip="python $HOME_BIN_DIR/pip.pyz"

# This one clears the scrollback buffer
# Without it, I can run "clear" but still scroll back past the top
alias clear="clear && printf '\e[3J'"
alias cl="clear"
. "$HOME/.cargo/env"

echo
FILE=${HOME_BIN_DIR}/neofetch
if test -f "$FILE"; then
    neofetch
fi
